name: Java cross-version tests

on:
  push:
    branches:
      - master
      - "szpak/**"
      - "marc/**"
  pull_request:
    branches:
      - '*'
  merge_group:

jobs:
  openjdk:
    strategy:
      matrix:
        jdk: [11, 17]
    name: "OpenJDK ${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'zulu'

      - uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4

      # Workaround https://github.com/ajoberstar/gradle-stutter/issues/22
      - name: Reduce number of Gradle regressions builds
        run: |
          # Keep only the last Gradle version per Stutter matrix; for each line this transformation is done:
          # java11=6.2.2,6.9.4,7.0.2,7.6.1,8.0.2,8.1.1,8.2-rc-1
          # ->
          # java11=8.2-rc-1
          # The trick is that \2 will greedily eat everything before the last comma.
          sed -r 's/^(.*?)=(.*),(.*)$/\1=\3/g' -i stutter.lockfile
          cat stutter.lockfile

      - name: Test cross Java versions compatibility
        run: |
          ./gradlew --version
          ./gradlew --stacktrace build compatTestJava${{ matrix.jdk }}
