name: Java cross-version tests

on:
  push:
    branches:
      - master
      - "szpak/**"
      - "marc/**"
  pull_request:
    branches:
      - '*'

jobs:
  openjdk:
    strategy:
      matrix:
        jdk: [8, 11, 15]
    name: "OpenJDK ${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      # Workaround https://github.com/ajoberstar/gradle-stutter/issues/22
      - name: Reduce number of Gradle regressions builds
        run: |
          for l in .stutter/*.lock; do
            echo $l
            echo "$(cat $l | grep -v "^#" | tail -1)" > $l
            cat $l
          done
      - name: Test cross Java versions compatibility
        run: |
          ./gradlew --version
          ./gradlew --stacktrace build
